gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "magenta"
      - "bold"
    inactiveBorderColor:
      - "default"
    optionsTextColor:
      - "blue"
    selectedLineBgColor:
      - "bold"
    cherryPickedCommitBgColor:
      - "default"
    cherryPickedCommitFgColor:
      - "magenta"
    unstagedChangesColor:
      - "red"
    defaultFgColor:
      - "default"
    searchingActiveBorderColor:
      - "yellow"
      - "bold"
git:
  diffRenderers:
    - colorArg: always
      command: delta-system --paging=never
